---
# Doc: https://helm.sh/fr/docs/intro/install/
- hosts: kube
  become: true
  tasks:
    - name: "Add Apt signing key"
      ansible.builtin.apt_key:
        url: https://baltocdn.com/helm/signing.asc
        keyring: "{{ helm_gpg_path }}"
        state: present

    - name: "Add helm repository"
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64 signed-by={{ helm_gpg_path }}] https://baltocdn.com/helm/stable/debian all main"
        state: present

    - name: "helm installation"
      ansible.builtin.apt:
        name: "helm"
        state: present
        update_cache: true

    - name: "Repo configuration"
      become: false
      command:
        cmd: "helm repo add stable https://charts.helm.sh/stable"

    - name: "Copy helm Chart"
      copy:
        src: "{{ playbook_dir }}/../helm-charts/sre-hiring"
        dest: "/opt/helm-charts"
        owner: debian
        group: debian

    - name: "Install chart"
      become: false
      command:
        cmd: "helm install test sre-hiring"
        chdir: "/opt/helm-charts"
      when: helm_install | bool | default(false)

    - name: "Upgrade chart"
      become: false
      command:
        cmd: "helm upgrade test sre-hiring"
        chdir: "/opt/helm-charts"
      when: helm_upgrade | bool | default(true)
